#!/usr/bin/env node parkbot
const rawData = require("./airgarage-data");
const data = JSON.parse(rawData);

const args = process.argv.filter((val, index) => index >= 3);
const pathToData = args[0];
const command = args[1];
const userInput = args[2];

function mapNames(mapData) {
  return mapData.map(location => location.name)
}

function returnData() {
  let result;

  if (pathToData === 'airgarage-data.json') {
    if (command === 'locate') {
      result = data.filter(location => location.address.state === userInput);
    }

    if (command === 'find_price_hourly_lte') {
      result = data.filter(location => location.price_hourly < userInput)
    }
    
    if (command === 'find_price_hourly_gt') {
      result = data.filter(location => location.price_hourly > userInput)
    }
  }
  
  console.log(mapNames(result))
} 

returnData();